FROM        python:3.9

# 환경 변수
ENV         LANG C.UTF-8
ENV         PYTHONUNBUFFERED 1
ENV         APP_ENV FLOWER

# 라이브러리 설치
RUN         apt-get update -y
COPY        ./requirements/requirements.flower.txt /app/requirements.txt
RUN         pip install -U pip
RUN         pip install -r /app/requirements.txt

# 프로젝트 폴더로 이동
WORKDIR     /app

# 프로젝트 실행
CMD         celery -A conf.celery flower --port=80

EXPOSE      80