FROM        python:3.9

# 환경 변수
ENV         LANG C.UTF-8
ENV         PYTHONUNBUFFERED 1
ENV         APP_ENV API

# 라이브러리 설치
COPY        ./requirements/requirements.api.txt /app/requirements.txt
RUN         pip install -U pip
RUN         pip install -r /app/requirements.txt

# 프로젝트 폴더로 이동
WORKDIR     /app

# 프로젝트 실행
CMD         uvicorn main:app --reload --port 80 --host 0.0.0.0

EXPOSE      80